---
# GitHub Copilot Setup Steps for Newgen
# This file configures the environment setup for GitHub Copilot coding agent
# Note: Some steps will only work once the project structure is initialized

steps:
  - name: Verify Node.js version
    run: node --version
    description: Ensure Node.js v14 or higher is available
    
  - name: Check npm version
    run: npm --version
    description: Verify npm package manager is available
    
  - name: Install Node.js dependencies
    run: |
      if [ -f "package.json" ]; then
        npm install
      else
        echo "No package.json found - project structure not yet initialized"
      fi
    description: Install required npm packages if package.json exists

# Optional: Add environment variables if needed
# env:
#   NODE_ENV: development

# Optional: Add setup for specific tools or services
# - name: Setup additional tools
#   run: |
#     # Add any additional setup commands here
#     echo "Environment ready for Newgen development"
